backend/game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('pongCanvas/', views.pongCanvas, name='pongCanvas'),
    path('breakoutCanvas/', views.breakoutCanvas, name='breakoutCanvas'),
    path('gameChoice/', views.gameChoice, name='gameChoice'),
    path('optionsPong/', views.optionsPong, name='optionsPong'),
    path('optionsBreakout/', views.optionsBreakout, name='optionsBreakout'),
    path('bracket/', views.bracket, name='bracket'),
    path('saveMatch/', views.saveMatch, name='saveMatch'),
]

backend/game/models.py
from django.db import models
from users.models import User

# Create your models here.
class Match(models.Model):
    player1 = models.CharField(max_length=15)
    score1 = models.IntegerField()
    player2 = models.CharField(max_length=15)
    score2 = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    dateTime = models.CharField(max_length=30)
    color = models.CharField(max_length=10)

backend/game/views.py
from django.shortcuts import render
from django.http import JsonResponse
from game.models import Match
from django.utils.translation import gettext as _  # Import pour les traductions
import json
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def pongCanvas(request):
    # Récupérer les données des joueurs
	if not request.headers.get('HX-Request'):
		return render(request, '403.html', status=403)
	players_raw = request.GET.get('players')
	game = request.GET.get('game')
	#print("game:", game)
	return render(request, 'partials/canvas.html', {'players': players_raw, 'game': game})

def breakoutCanvas(request):
	# Récupérer les données des joueurs
	if not request.headers.get('HX-Request'):
		return render(request, '403.html', status=403)
	players_raw = request.GET.get('players')
	game = request.GET.get('game')
	#print("game:", game)
	#print("map", request.GET.get('map'))
	return render(request, 'partials/canvas.html', {'players': players_raw, 'game': game})

@login_required
def gameChoice(request):
	return render(request, 'partials/gameChoice.html')

@login_required
def optionsPong(request):
    user = request.user
    friendsList = user.friends.all()
    #print("yoyoyo")
    if request.headers.get('HX-Request'):
        return render(request, 'partials/options-pong.html', {
		'user': user, 
		'friendsList': friendsList,
		'message': _('Select your options for Pong')
	    })
    else:
        return render(request, 'optionsGameNotPartial.html', {
            'game': 'pong',
            'user': request.user,
            'friendsList': request.user.friends.all(),
            'message': _('Select your options for Pong')
            })

@login_required
def optionsBreakout(request):
    user = request.user
    friendsList = user.friends.all()
    #print("yoyoyo")
    if request.headers.get('HX-Request'):
        return render(request, 'partials/options-breakout.html', {
			'user': user, 
			'friendsList': friendsList,
			'message': _('Select your options for Breakout')  # Exemple de message traduisible
        })
    else:
        return render(request, 'optionsGameNotPartial.html', {
            'game': 'breakout',
            'user': request.user,
            'friendsList': request.user.friends.all(),
            'message': _('Select your options for Pong')
            })




def bracket(request):
	# Récupérer les données des joueurs
	if request.method == 'GET':
		players_raw = json.loads(request.GET.get('players'))
		players2 = []
		players3 = []
		players4 = []
		
		game = request.GET.get('game')
		#print("map", map)
		for players in players_raw:
			if players['win'] >= 1:
				if len(players_raw) == 2:
					players['score'][1] = 'w'
				players2.append(players)
			if players['win'] >= 2:
				if len(players_raw) == 4:
					players['score'][2] = 'w'
				players3.append(players)
			if players['win'] >= 3:
				if len(players_raw) == 8:
					players['score'][3] = 'w'
				players4.append(players)
							
		return render(request, 'partials/bracket.html', {
			"players": players_raw, 
			"players2": players2, 
			"players3": players3,
            "players4": players4,
			"game": game,
			'title': _('Bracket View'),  # Exemple de traduction
		})
	else:
		return render(request, '403.html', status=403)

def saveMatch(request):
	if request.method == "POST":
		try:
			data = json.loads(request.body)
		except json.JSONDecodeError:
			return JsonResponse({'error': 'Invalid JSON'}, status=400)
		
		user = request.user

		if user.username != data['player1'] and user.username != data['player2']:
			return JsonResponse({'error': 'You are not one of the players'}, status=400)

		friendList = user.friends.all()
		
		try:
			if user.username == data['player1'] and data['score1'] > data['score2']:
				# #print("user", user)
				color = "victoire"
				user.win += 1
				user.bounce += data['bounce1']
				user.bonus += data['bonus1']
				user.score += data['score1']
			elif user.username == data['player2'] and data['score2'] > data['score1']:
				# #print("user", user)
				color = "victoire"
				user.win += 1
				user.bounce += data['bounce2']
				user.bonus += data['bonus2']
				user.score += data['score2']
			elif user.username == data['player1'] and data['score1'] < data['score2']:
				# #print("user", user)
				color = "defaite"
				user.lose += 1
				user.bounce += data['bounce1']
				user.bonus += data['bonus1']
				user.score += data['score1']
			else:
				# #print("user", user)
				color = "defaite"
				user.lose += 1
				user.bounce += data['bounce2']
				user.bonus += data['bonus2']
				user.score += data['score2']
			user.gamePlayed += 1
			user.save()
			newMatch = Match.objects.create(player1=data['player1'], score1=data['score1'], player2=data['player2'], score2=data['score2'], user=user, dateTime=data['dateTime'], color=color)
			newMatch.save()
			# #print("user match:", user.match_set.all())
			for friend in friendList:
				if friend.username == data['player1'] or friend.username == data['player2']:
					friendscolor = "defaite" if color == "victoire" else "victoire"
					newMatchFriend = Match.objects.create(player1=data['player1'], score1=data['score1'], player2=data['player2'], score2=data['score2'], user=friend, dateTime=data['dateTime'], color=friendscolor)
					newMatchFriend.save()
		except KeyError as e:
			return JsonResponse({'error': f'Missing field: {e}'}, status=400)
		return JsonResponse(data)
	else:
		return render(request, "403.html", status=403)

backend/game/templates/optionsGameNotPartial.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html data-bs-theme="light" lang="en">

<head>
     <script src="https://unpkg.com/htmx.org@1.8.4" defer></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>transcendence</title>
	<link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'users/styles/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'users/styles/fixed-navbar-starting-with-transparency-styles.css' %}">
    <link rel="stylesheet" href="{% static 'users/styles/untitled.css' %}">
	<link rel="stylesheet" href="{% static 'users/styles/style.css' %}">
    <link rel="stylesheet" href="{% static 'users/styles/login-form---Ambrodu-register.css' %}">
	<link rel="stylesheet" href="{% static 'users/styles/profile.css' %}">
	<link rel="stylesheet" href="{% static 'game/styles/background.css' %}">
	<link rel="stylesheet" href="{% static 'game/styles/gameChoice.css' %}">
	<link rel="stylesheet" href="{% static 'game/styles/options-pong.css' %}">
	<link rel="stylesheet" href="{% static 'game/styles/options-breakout.css' %}">
    <link rel="stylesheet" href="{% static 'game/styles/tournament.css' %}">
    <script src="{% static 'users/scripts/jQuery.js' %}" defer></script>
    <script src="{% static 'users/scripts/navigate.js' %}" defer></script>
    <script src="{% static 'users/scripts/bootstrap.min.js' %}" defer></script>
    <script src="{% static 'users/scripts/fixed-navbar-starting-with-transparency-script.js' %}" defer></script>
	<script src="{% static 'game/scripts/optionsGames.js' %}" defer></script>
	<script src="{% static 'game/scripts/DrawStars.js' %}" defer></script>
	<script src="{% static 'game/scripts/const.js' %}" defer></script>
    <script src="{% static 'game/scripts/tournamentAnimation.js' %}" defer></script>
    <script src="{% static 'game/scripts/tournament.js' %}" defer></script>
	<script src="{% static 'game/scripts/gameLoader.js' %}" defer></script>
    <script src="{% static 'game/scripts/ia.js' %}" defer></script>
	<script src="{% static 'game/scripts/breakout.js' %}" defer></script>
	<script src="{% static 'game/scripts/pong.js' %}" defer></script>
    <script src="{% static 'game/scripts/bracket.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{% static 'users/scripts/statsChart.js' %}"></script>


</head>

<body class="animated-bg" style="height: 100vh;">
	<canvas id="star-canvas"></canvas>
    {% include 'partials/navbar.html' %}
	{% if game == "breakout" %}
		{% include 'partials/options-breakout.html' %}
	{% else %}
		{% include 'partials/options-pong.html' %}
	{% endif %}
</body>

</html>

backend/game/templates/partials/bracket.html
{% load i18n %}
<div id="tmp" class="tmp">
    <div id="tournament" class="tournament-bracket">
        <div class="round">
            {% for player in players %}
                {% if forloop.counter0|divisibleby:2 %}
                    <span class="inGame" style="font-family: 'Press Start 2P'; color: #fff;">
                        {% if forloop.counter0 == 0 %}
                            1
                        {% elif forloop.counter0 == 2 %}
                            2
                        {% elif forloop.counter0 == 4 %}
                            3
                        {% elif forloop.counter0 == 6 %}
                            4
                        {% endif %}
                    </span>
                    <div class="match-container match">
                {% endif %}
                    <div class="bracket-player">
                        {{ player.name }} <span class="score">{{ player.score.0 }}</span>
                    </div>
                {% if forloop.counter0|divisibleby:2 != 1 %}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <!-- ROUND II -->
        <div class="round">
            {% for player in players2 %}
                {% if forloop.counter0|divisibleby:2 %}
                    <span class="inGame" style="font-family: 'Press Start 2P'; color: #fff;">
                        {% if forloop.counter0 == 0 %}
                            1
                        {% elif forloop.counter0 == 2 %}
                            2
                        {% elif forloop.counter0 == 4 %}
                            3
                        {% elif forloop.counter0 == 6 %}
                            4
                        {% endif %}
                    </span>
                    <div class="match-container match">
                {% endif %}
                    <div class="bracket-player">
                        {{ player.name }} <span class="score">{{ player.score.1 }}</span>
                    </div>
                {% if forloop.counter0|divisibleby:2 != 1 %}
                    </div>
                {% endif %}
            {% endfor %}
            {% if players2|length == 1 or players2|length == 3 %}
                </div>
            {% endif %}
        </div>
        <!-- ROUND III -->
        <div class="round">
            {% for player in players3 %}
                {% if forloop.counter0|divisibleby:2 %}
                    <span class="inGame" style="font-family: 'Press Start 2P'; color: #fff;">
                        {% if forloop.counter0 == 0 %}
                            1
                        {% elif forloop.counter0 == 2 %}
                            2
                        {% elif forloop.counter0 == 4 %}
                            3
                        {% elif forloop.counter0 == 6 %}
                            4
                        {% endif %}
                    </span>
                    <div class="match-container match">
                {% endif %}
                    <div class="bracket-player">
                        {{ player.name }} <span class="score">{{ player.score.2 }}</span>
                    </div>
                {% if forloop.counter0|divisibleby:2 != 1 %}
                    </div>
                {% endif %}
            {% endfor %}
            {% if players3|length == 1 %}
                </div>
            {% endif %}
        </div>
    </div>
    {% if players|length == 2 and players2|length == 1 %}
        <button class="continu-button" hx-get="{% url 'game:gameChoice' %}" hx-target="#tmp" hx-swap="outerHTML"
            style="cursor: pointer; z-index: 3;">
            {% trans "Continue" %}
        </button>
    {% elif players|length == 4 and players3|length == 1 %}
        <button class="continu-button" hx-get="{% url 'game:gameChoice' %}" hx-target="#tmp" hx-swap="outerHTML"
            style="cursor: pointer; z-index: 3;">
            {% trans "Continue" %}
        </button>
    {% elif players|length == 8 and players4|length == 1 %}
        <button class="continu-button" hx-get="{% url 'game:gameChoice' %}" hx-target="#tmp" hx-swap="outerHTML"
            style="cursor: pointer; z-index: 3;">
            {% trans "Continue" %}
        </button>
    {% elif game == 'breakout' %}
        <button class="continu-button" hx-get="{% url 'game:breakoutCanvas' %}" hx-target="#tmp" hx-swap="outerHTML"
            hx-vals='{"players": "{{ players|escapejs }}", "game": "breakout"}' style="cursor: pointer; z-index: 3;">
            {% trans "Continue" %}
        </button>
    {% elif game == 'pong' %}
        <button class="continu-button" hx-get="{% url 'game:pongCanvas' %}" hx-target="#tmp" hx-swap="outerHTML"
            hx-vals='{"players": "{{ players|escapejs }}", "game": "pong"}' style="cursor: pointer; z-index: 3;">
            {% trans "Continue" %}
        </button>
    {% endif %}
</div>

backend/game/templates/partials/canvas.html
{% load static %}
{% load i18n %}

<div id="containerCanvas" class="tmp">
    <canvas id="{{ game }}Canvas" width="800" height="600" data-players="{{ players }}"></canvas>
    <button class="continu-button popito" id="gameButton" hx-get="{% url 'game:bracket' %}" hx-target="#containerCanvas" hx-swap="outerHTML" hx-vals=""
    style="cursor: pointer; position: relative; z-index: 3;">
        <div id="bigWin"></div>
        {% trans "Continue" %}
    </button>
    <script>
        const translations = {
            win: "{% trans 'win!' %}"
        };
    </script>   
</div>

backend/game/templates/partials/dropdownFriend.html
{% load i18n %}
{% if friends %}
    {% for friend in friends %}
        <button class="dropdown-item" type="button" onclick="addFriend('{{ friend.username }}')">
            <li>{{ friend.username }}</li>
        </button>
    {% endfor %}
{% else %}
    <li>{% trans "No friends" %}</li>
{% endif %}

backend/game/templates/partials/gameChoice.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<!DOCTYPE html>

<container id="gameChoice">
<div class="content">
    <h1 class="game-title">{% trans "Time to play!" %}</h1>
        <div class="boxes-container">
            <div class="box box1">
                <img src="{% static 'game/images/pong2.jpg' %}" hx-get="{% url 'game:optionsPong' %} " hx-target="#gameChoice" hx-swap="outerHTML" hx-push-url="true">
            </div>
            <div class="box box2">
                <img src="{% static 'game/images/casseBrick2.jpg' %}" hx-get="{% url 'game:optionsBreakout' %} " hx-target="#gameChoice" hx-swap="outerHTML" hx-push-url="true">
            </div>
        </div>
    </div>
</container>
{% endblock content %}

backend/game/templates/partials/options-breakout.html
{% extends 'partials/optionsGame.html' %}
{% load i18n %}
{% block content %}
    <div class="maps">
        <button class="btn btn-map">Map 1</button>
        <button class="btn btn-map">Map 2</button>
        <button class="btn btn-map">Map 3</button>
    </div>
    <button class="btn btn-success btn-lg" hx-get="{% url 'game:bracket' %}" hx-target="#gameOption" hx-vals="js:{'players': shufflePlayer(), 'game': 'breakout'}" hx-swap="outerHTML" onclick="selectedMap()">
        {% trans "Start" %}
    </button>
    <script>
        const buttons = document.querySelectorAll('.btn-map');
    
        buttons.forEach(button => {
            button.addEventListener('click', function() {
                buttons.forEach(btn => btn.classList.remove('selected'));
                this.classList.add('selected');
            });
        });
        function selectedMap() {
            const maps = document.querySelectorAll('.btn-map');
            for (let i = 0; i < maps.length; i++) {
                if (maps[i].classList.contains('selected')) {
                    map = i + 1;
                }
            }
            map = map || 1;
        }
    </script>    
{% endblock content %}

backend/game/templates/partials/options-pong.html
{% extends 'partials/optionsGame.html' %}
{% load i18n %}
{% block content %}
	<button class="btn btn-success btn-lg" hx-get="{% url 'game:bracket' %}" hx-target="#gameOption" hx-vals="js:{'players': shufflePlayer(), 'game': 'pong'}" hx-swap="outerHTML">
		{% trans "Start" %}
	</button>
{% endblock content %}

backend/game/templates/partials/optionsGame.html
{% load i18n %}
{% load static %}
<container id="gameOption">
<div class="content">
<div class="container py-5">
<h1 class="mb-4-title">{% trans "Options" %}</h1>

<div class="card mb-4">
	<div class="card-body">
		<h5 class="card-title">{% trans "Players" %}</h5>
		<div id="players-container">
			<div class="player-input mb-3">
				<div class="input-group">
					<span class="input-group-text">{% trans "Player 1" %}</span>
					<input type="text" class="form-control player" placeholder="{{user.username}}" value="{{user.username}}" disabled>
					<input type="color" class="form-control form-control-color" value="#ff0000" title="{% trans "Choose color" %}">
				</div>
			</div>
		</div>
		<div class="btn-group" role="group">
			<button class="btn btn-primary" onclick="addPlayer()">
				<i class="fas fa-plus"></i> {% trans "Add player" %}
			</button>
			<div class="btn-group" role="group">
				<button 
					type="button" 
					class="btn btn-primary dropdown-toggle" 
					data-bs-toggle="dropdown" 
					aria-expanded="false">
					<i class="fas fa-plus"></i> {% trans "Add friend" %}
				</button>
				<ul class="dropdown-menu" id="friend-dropdown">
					{% include 'partials/dropdownFriend.html' with friends=friendsList %}
				</ul>
			</div>
			<button class="btn btn-danger" onclick="removePlayer()">
				<i class="fas fa-minus"></i> {% trans "Delete player" %}
			</button>
		</div>
	</div>
</div>

<div class="card mb-4">
	<div class="card-body">
		<h5 class="card-title">{% trans "Game options" %}</h5>
		<div class="form-check form-switch">
			<input class="form-check-input" type="checkbox" id="bonusSwitch">
			<label class="form-check-label" for="bonusSwitch">{% trans "Enable bonuses" %}</label>
		</div>
	</div>
</div>
{% block content %}
{% endblock %}
</div>
</container>
<script>
	function shufflePlayer() {
    let listPlayer = Array.from(document.querySelectorAll('.player'));
	let color = Array.from(document.querySelectorAll('.form-control-color'));
    // Convertir les inputs en objets joueurs
	listPlayer = Array.from(listPlayer).map((input, index) => {
		//make a true copy of input
		let input1 = input.cloneNode(true);
		fixInput(input1);
		return {
			name: input1.value || 'Player' + (index + 1),
			username: input.value || 'Player' + (index + 1),
			score: [0, 0, 0, 0],
			round: 0,
			win: 0,
			loose: 0,
			isIa: 0,
			color: color[index].value
		};
	});

	//consol.log('listPlayer = ', listPlayer);
    // Ajouter des IA si le nombre nest pas une puissance de 2
	if (listPlayer.length === 1) {
		listPlayer.push({
			name: '{% trans "IA1" %}    ',
			username: '{% trans "IA1" %}    ',
			score: [0, 0, 0, 0],
			round: 0,
			win: 0,
			loose: 0,
			isIa: 1,
			color: '#ff0000'
		});
	} else if (![2, 4, 8].includes(listPlayer.length)) {
		const targetLength = Math.pow(2, Math.ceil(Math.log2(listPlayer.length)));
		for (let i = listPlayer.length; i < targetLength; i++) {
			listPlayer.push({
				name: '{% trans "IA" %}' + (i - listPlayer.length + 1),
				username: '{% trans "IA1" %}' + (i - listPlayer.length + 1),
				score: [0, 0, 0, 0],
				round: 0,
				win: 0,
				loose: 0,
				isIa: 1,
				color: '#ff0000'
			});
		}
	}

    // Mélanger la liste
    for (let i = listPlayer.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [listPlayer[i], listPlayer[j]] = [listPlayer[j], listPlayer[i]];
    }
	let bonus = document.getElementById('bonusSwitch').checked;
	if (bonus)
		isBonus = true;
    return JSON.stringify(listPlayer);
}


		    window.addEventListener('popstate', function(event) {
        // Récupérer l'URL actuelle
        const currentPath = window.location.pathname;
        
        // Vérifier si l'URL correspond à /gameOption/
        if (currentPath.startsWith('/gameOption/')) {
            // Effectuer un GET vers la vue gameOption
            htmx.ajax('GET', currentPath, '#content');
        }
    });
	    window.addEventListener('popstate', function(event) {
        // Récupérer l'URL actuelle
        const currentPath = window.location.pathname;
        
        // Vérifier si l'URL correspond à /gameOption/
        if (currentPath.startsWith('/gameOption/')) {
            // Effectuer un GET vers la vue gameOption
            htmx.ajax('GET', currentPath, '#content');
        }
    })
	    window.addEventListener('popstate', function(event) {
        // Récupérer l'URL actuelle
        const currentPath = window.location.pathname;
        
        // Vérifier si l'URL correspond à /gameOption/
        if (currentPath.startsWith('/gameOption/')) {
            // Effectuer un GET vers la vue gameOption
            htmx.ajax('GET', currentPath, '#content');
        }
    });
// trunc the name if up to 7 characters and add '.' if its to long or add space up to 7 characters if its to short
function fixInput(input) {
	if (input.value.length > 7) {
		input.value = input.value.slice(0, 7) + '.';
	}
	return input;
}

</script>